# P6Spy Configuration
# 实际JDBC驱动
driverlist=com.mysql.cj.jdbc.Driver

# 日志格式
dateformat=yyyy-MM-dd HH:mm:ss
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=execution time:%(executionTime) ms | %(category) | %(sqlSingleLine)

# 过滤器（排除一些无关SQL）
excludecategories=info,debug,result,resultset

# 慢SQL阈值（毫秒）
outagedetection=true
outagedetectioninterval=2
